// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ClearCorrectMistakes():Promise<void>;

export function GenerateAIExplanation(arg1:number,arg2:boolean):Promise<string>;

export function GetCorrectMistakesCount():Promise<number>;

export function GetGrid():Promise<Array<main.GridItem>>;

export function GetQuestion(arg1:number):Promise<main.QuestionView>;

export function GetStats():Promise<main.Stats>;

export function RemoveFromMistakeBook(arg1:number):Promise<void>;

export function SetMistakeMode(arg1:boolean):Promise<void>;

export function SubmitAnswer(arg1:number,arg2:string):Promise<main.SubmitResult>;

export function ToggleMark(arg1:number):Promise<boolean>;
