// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearCorrectMistakes() {
  return window['go']['main']['App']['ClearCorrectMistakes']();
}

export function GenerateAIExplanation(arg1, arg2) {
  return window['go']['main']['App']['GenerateAIExplanation'](arg1, arg2);
}

export function GetCorrectMistakesCount() {
  return window['go']['main']['App']['GetCorrectMistakesCount']();
}

export function GetGrid() {
  return window['go']['main']['App']['GetGrid']();
}

export function GetQuestion(arg1) {
  return window['go']['main']['App']['GetQuestion'](arg1);
}

export function GetStats() {
  return window['go']['main']['App']['GetStats']();
}

export function RemoveFromMistakeBook(arg1) {
  return window['go']['main']['App']['RemoveFromMistakeBook'](arg1);
}

export function SetMistakeMode(arg1) {
  return window['go']['main']['App']['SetMistakeMode'](arg1);
}

export function SubmitAnswer(arg1, arg2) {
  return window['go']['main']['App']['SubmitAnswer'](arg1, arg2);
}

export function ToggleMark(arg1) {
  return window['go']['main']['App']['ToggleMark'](arg1);
}
